config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :quotes
  resources :leads
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "residential" => "pages#residential"
  
  get "commercial" => "pages#commercial"

  get "quote" => "pages#quote"

  post "quote" => "quotes#create"

  get "/"  => "pages#index"

  post "index" => "leads#create"
  
  root to:'pages#index'

  get '/charts' => 'charts#chart'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/address.rb
class Address < ApplicationRecord
   has_one :building
   has_one :customer
end

app/models/battery.rb
class Battery < ApplicationRecord
   has_many :column
   belongs_to :building
end

app/models/building.rb
class Building < ApplicationRecord
   belongs_to :customer
   belongs_to :address
   has_many :battery
   has_one :building_detail
end

app/models/column.rb
class Column < ApplicationRecord
  belongs_to :battery
  has_many :elevator
end

app/models/customer.rb
class Customer < ApplicationRecord
   belongs_to :user
   belongs_to :address
   has_many :building
end

app/models/dim_customer.rb
class DimCustomer < DwhRecord
end

app/models/dwh_manager.rb
class DwhManager < DwhRecord
    self.abstract_class = true

  connects_to database: { mysql2: :animals, postgres: :animals_replica }

end

app/models/dwh_record.rb
class DwhRecord < ActiveRecord::Base
  self.abstract_class = true
  establish_connection :"dwh_#{Rails.env}"
end

app/models/elevator.rb
class Elevator < ApplicationRecord
    belongs_to :column
end

app/models/employee.rb
class Employee < ApplicationRecord
    belongs_to :user
end

app/models/fact_contact.rb
class FactContact < DwhRecord
end

app/models/fact_elevator.rb
class FactElevator < DwhRecord
end

app/models/fact_quote.rb
class FactQuote < DwhRecord
end

app/models/lead.rb
class Lead < ApplicationRecord
    has_one_attached :workfile
end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :employee
  has_many :customer
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/lead_helper.rb
module LeadHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Rocket Elevators</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="icon" href="assets/images/Logo/web_logo.png">
    <meta charset="utf-8" />
    <title>Rocket Elevators - Commercial and Corporate services</title>
    <meta name="description" content="" />
    <meta name="Author" content="Dorin Grigoras [www.stepofweb.com]" />

    <%
=begin%>
    <!-- mobile settings -->
    <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0" />
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->

    <!-- WEB FONTS : use %7C instead of | (pipe) -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600%7CRaleway:300,400,500,600,700%7CLato:300,400,400italic,600,700" rel="stylesheet" type="text/css" />

    <!-- CORE CSS -->
    <link href="assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />

    <!-- REVOLUTION SLIDER -->
    <link href="assets/plugins/slider.revolution/css/extralayers.css" rel="stylesheet" type="text/css" />
    <link href="assets/plugins/slider.revolution/css/settings.css" rel="stylesheet" type="text/css" />

    <!-- THEME CSS -->
    <link href="assets/css/essentials.css" rel="stylesheet" type="text/css" />
    <link href="assets/stylesheets/layout.css" rel="stylesheet" type="text/css" />

    <!-- PAGE LEVEL SCRIPTS -->
    <link href="assets/css/header-1.css" rel="stylesheet" type="text/css" />
    <link href="assets/css/color_scheme/blue.css" rel="stylesheet" type="text/css" id="color_scheme" />

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,600|Lato:400,700|Nunito:300,400" rel="stylesheet">

    <!-- LayerSlider styles -->
    <link rel="stylesheet" href="assets/css/layerslider/layerslider.css" type="text/css">

    <!-- External libraries: jQuery & GreenSock -->
    <script src="assets/js/layerslider/jquery.js" type="text/javascript"></script>
    <script src="assets/js/layerslider/greensock.js"></script>
    <%
=end%>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
</head>



<body class="smoothscroll enable-animation">
    <!-- wrapper -->
    <div id="wrapper">

        <!-- 
				AVAILABLE HEADER CLASSES
				Default nav height: 96px
				.header-md 		= 70px nav height
				.header-sm 		= 60px nav height
				.b-0 		= remove bottom border (only with transparent use)
				.transparent	= transparent header
				.translucent	= translucent header
				.sticky			= sticky header
				.static			= static header
				.dark			= dark header
				.bottom			= header on bottom
				
				shadow-before-1 = shadow 1 header top
				shadow-after-1 	= shadow 1 header bottom
				shadow-before-2 = shadow 2 header top
				shadow-after-2 	= shadow 2 header bottom
				shadow-before-3 = shadow 3 header top
				shadow-after-3 	= shadow 3 header bottom
				.clearfix		= required for mobile menu, do not remove!
				Example Usage:  class="clearfix sticky header-sm transparent b-0"
			-->
        <div id="header" class="navbar-toggleable-md sticky header-md clearfix">
            <% flash.each do |key, value| %>
            <div class="alert alert -<%= key %> col-md-8 col md-offset-2-main"><%= value %></div>
            <%end%>

            <!-- TOP NAV -->
            <header id="topNav">
                <div class="container">

                    <!-- Mobile Menu Button -->
                    <button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Logo -->
                    <a class="logo float-left scrollTo" href="#top">
                        <%= image_tag("Logo/logo.png",  width:"150px", alt:"Rocket Elevators Logo")%>
                        <!--img src="assets/images/Logo/logo.png" alt="Rocket Elevators Logo" width="150" /-->
                    </a>

                    <!-- 
							Top Nav 
							
							AVAILABLE CLASSES:
							submenu-dark = dark sub menu
						-->
                    <div class="navbar-collapse collapse float-right nav-main-collapse submenu-dark">
                        <nav class="nav-main">

                            <!-- 
									.nav-onepage
									Required for onepage navigation links
									
									Add .external for an external link!
								-->
                            <ul id="topMain" class="nav nav-pills nav-main nav-onepage">
                                <li class="active">
                                    <!-- HOME -->
                                    <a href="/">
                                        HOME
                                    </a>
                                </li>
                                <li>
                                    <!-- SERVICES -->
                                    <a href="/#services">
                                        SERVICES
                                    </a>
                                </li>
                                <li>
                                    <!-- PORTFOLIO -->
                                    <a href="/#portfolio">
                                        PORTFOLIO
                                    </a>
                                </li>
                                <li>
                                    <!-- NEWS -->
                                    <a href="/#news">
                                        NEWS
                                    </a>
                                </li>

                                <li>
                                    <!-- CLIENTS -->
                                    <a href="/#clients">
                                        CLIENTS
                                    </a>
                                </li>

                                <li>
                                    <!-- CONTACT -->
                                    <a href="/#contact">
                                        CONTACT
                                    </a>
                                </li>
                                <% if user_signed_in? %>
                                    <li class="nav-item">
                                        <%= link_to "SIGN OUT", destroy_user_session_path, method: :delete, class: 'nav-link' %>
                                    </li>
                                    <li class="nav-item">
                                        <%= link_to "ADMIN", rails_admin_url, class: 'nav-link' %>
                                    </li>
                                    <li>
										<!-- STATISTICS -->
										<a href="/chart">
											STATISTICS
										</a>
									</li>
                                <% else %>
                                    <li class="nav-item">
                                        <%= link_to "SIGN IN", new_user_session_path, class: 'nav-link' %>
                                    </li>
                                <% end %> 
                            </ul>
                        </nav>
                    </div>
                </div>
            </header>

            <!-- /Top Nav -->

        </div>

        <%= yield %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        
        <!-- FOOTER -->
        <footer id="footer">
            <div class="container">


                <div class="row">

                    <!-- col #1 -->
                    <div class="col-md-6">

                        <h3 class="letter-spacing-1">WHY US?</h3>

                        <!-- Small Description -->
                        <p>
                            We have the conviction that we create the most innovative and reliable products on the
                            market. Contact us today for any questions you might have.
                        </p>
                        <h2>(418) 555-1234</h2>
                    </div>
                    <!-- /col #1 -->

                    <!-- col #2 -->
                    <div class="col-md-2">

                        <h3 class="letter-spacing-1">EXPLORE</h3>

                        <li class="active">
                            <!-- HOME -->
                            <a href="/">
                                Home
                            </a>
                        </li>
                        <li>
                            <!-- SERVICES -->
                            <a href="/#services">
                                Services
                            </a>
                        </li>
                        <li>
                            <!-- PORTFOLIO -->
                            <a href="/#portfolio">
                                Portfolio
                            </a>
                        </li>
                        <li>
                            <!-- NEWS -->
                            <a href="/#news">
                                News
                            </a>
                        </li>

                        <li>
                            <!-- CLIENTS -->
                            <a href="/#clients">
                                Clients
                            </a>
                        </li>

                        <li>
                            <!-- CONTACT -->
                            <a href="/#contact">
                                Contact
                            </a>
                        </li>
                    </div>
                    <!-- /col #2 -->

                    <!-- col #3 -->
                    <div class="col-md-4">
                        <h3 class="letter-spacing-1">KEEP IN TOUCH</h3>

                        <!-- Newsletter Form -->
                        <a class="btn btn-blue btn-lg" href="/#contact">CONTACT US <i class="fa fa-angle-right"></i></a>

                        <!-- /Newsletter Form -->
                        <p>
                            <br>
                            <span class="block"><strong><i class="fa fa-map-marker"></i> Address:</strong>418-725
                                Boulevard Lebourgneuf, Québec, QC G2J 0C4, Canada</span>
                            <span class="block"><strong><i class="fa fa-phone"></i> Phone:</strong> <a href="tel:(418) 555-1234">(418) 555-1234 </a></span>
                            <span class="block"><strong><i class="fa fa-envelope"></i> Email:</strong> <a href="mailto:info@codeboxx.biz">info@codeboxx.biz</a></span>
                        </p>

                    </div>
                    <!-- /col #3 -->

                </div>


            </div>

            <div class="copyright">
                <div class="container">
                    <ul class="float-right m-0 list-inline mobile-block">
                        <li><a href="#">Terms &amp; Conditions</a></li>
                        <li>&bull;</li>
                        <li><a href="#">Privacy</a></li>
                    </ul>
                    &copy; All Rights Reserved, Rocket Elevators Inc.
                </div>
            </div>

        </footer>
        <!-- /FOOTER -->

    </div>
    <!-- /wrapper -->



    <!-- PRELOADER

    <div id="preloader">
        <div class="inner">
            <span class="loader"></span>
        </div>

    </div>
    <-- /PRELOADER --> 


   	<!-- JAVASCRIPT FILES -->
	<script>var plugin_path = 'assets/plugins/';</script>
	<script src="assets/plugins/jquery/jquery-3.3.1.min.js"></script>

	<script src="assets/js/scripts.js"></script>



	<!-- REVOLUTION SLIDER -->
	<script src="assets/plugins/slider.revolution/js/jquery.themepunch.tools.min.js"></script>
	<script src="assets/plugins/slider.revolution/js/jquery.themepunch.revolution.min.js"></script>
	<script src="assets/js/view/demo.revolution_slider.js"></script>

	<!-- PAGELEVEL SCRIPTS -->
	<script src="assets/js/contact.js"></script>

</body>

</html>
<%# <script type="text/javascript">
  $(document).ready(function () {
        $(window).scroll(function () {
          if ($(this).scrollTop() & gt; 600) {
            $(".scrollToTop").fadeIn(1000)
          } else {
            $(".scrollToTop").fadeOut(1000);
          }
        });

        //Click event to scroll to top
        $(".scrollToTop").click(function () {
          $('html, body').animate({
            scrollTop: 0
          }, 500);
          return false;
        });
      })
</script> %>

app/views/pages/commercial.html.erb
		<hr class="m-2" /><!-- 1px line separator -->
		<div class="text-center">
			<br>
			<a
				style="font-family:Poppins;font-size:50px;line-height:50px;color:#a01818;top:552px;left:883px;font-weight:600;">Commercial
				and Corporate Styles</a> <br><br>
			<p>Working place are where the people want to feel safe, and is where they spend a lot of time. At Rocket
				Elevators, we know that, an we want to take that to the next level. <br> Here is a little catalog with
				some of our designs, please feel free to <strong>contact us</strong> if you have any question.</p>
		</div>

		<hr class="m-2" /><!-- 1px line separator -->



		<!-- SLIDE SECTION -->

		<div id="layerslider" class="giantmargin" style="width:1280px;height:720px;max-width:1280px;">

			<div class="ls-slide" data-ls="bgsize:contain;duration:4000;transition2d:73;kenburnszoom:in;">
				<%= image_tag("Commercial/commercial1.jpg", height:"300px", alt:"vintage elevator", class:"ls-bg")%>
				<!--img height="300" src="assets/images/Commercial/commercial1.jpg" class="ls-bg" alt="vintage elevator"-->
				<p style="font-family:Poppins;font-size:50px;line-height:50px;color:#3d3d3d;top:552px;left:883px;font-weight:600;"
					class="ls-l"
					data-ls="offsetxin:-100%;durationin:600;delayin:400;easingin:easeOutQuint;clipin:0 0 0 100%;offsetxout:-100%;durationout:500;clipout:0 0 0 100%;parallaxlevel:0;">
					Vintage Style
				</p>
				<p style="letter-spacing:7px;font-family:Poppins;font-size:24px;line-height:24px;color:#a01818;top:602px;left:885px;font-weight:700;"
					class="ls-l"
					data-ls="offsetxin:-100%;durationin:600;delayin:400;easingin:easeOutQuint;clipin:0 0 0 100%;offsetxout:-100%;durationout:500;clipout:0 0 0 100%;parallaxlevel:0;">
					Iron and glass.
				</p>
			</div>

			<div class="ls-slide" data-ls="bgsize:contain;duration:4000;transition2d:73;kenburnszoom:in;">
				<%= image_tag("Commercial/commercial2.jpeg", height:"300px", alt:"elevator", class:"ls-bg")%>
				<!--img height="300" src="assets/images/Commercial/commercial2.jpeg" class="ls-bg" alt="elevator"-->
				<p style="font-weight:600;overflow:hidden;font-family:Poppins;font-size:50px;line-height:50px;color:#3d3d3d;top:552px;left:883px;"
					class="ls-l"
					data-ls="offsetxin:-100%;durationin:600;delayin:400;easingin:easeOutQuint;clipin:0 0 0 100%;offsetxout:-100%;durationout:500;clipout:0 0 0 100%;parallaxlevel:0;">
					Clean Style
				</p>
				<p style="letter-spacing:7px;font-family:Poppins;font-size:24px;line-height:24px;color:#a01818;top:602px;left:885px;font-weight:700;"
					class="ls-l"
					data-ls="offsetxin:-100%;durationin:600;delayin:400;easingin:easeOutQuint;clipin:0 0 0 100%;offsetxout:-100%;durationout:500;clipout:0 0 0 100%;parallaxlevel:0;">
					Stainless steel.
				</p>
			</div>

			<div class="ls-slide" data-ls="bgsize:contain;duration:4000;transition2d:73;kenburnszoom:in;">
				<%= image_tag("Commercial/commercial3.jpg", height:"1000px", width:"1000px", alt:"elevator", class:"ls-bg")%>
				<!--img width="1000" height="1000" src="assets/images/Commercial/commercial3.jpg" class="ls-bg"
					alt="elevator"-->
				<p style="font-family:Poppins;font-size:50px;line-height:50px;color:#3d3d3d;top:552px;left:883px;font-weight:600;"
					class="ls-l"
					data-ls="offsetxin:-100%;durationin:600;delayin:400;easingin:easeOutQuint;clipin:0 0 0 100%;offsetxout:-100%;durationout:500;clipout:0 0 0 100%;parallaxlevel:0;">
					Elegant Style
				</p>
				<p style="letter-spacing:7px;font-family:Poppins;font-size:24px;line-height:24px;color:#a01818;top:602px;left:885px;font-weight:700;"
					class="ls-l"
					data-ls="offsetxin:-100%;durationin:600;delayin:400;easingin:easeOutQuint;clipin:0 0 0 100%;offsetxout:-100%;durationout:500;clipout:0 0 0 100%;parallaxlevel:0;">
					Wood, ceramic and<br> stainless steel.
				</p>
			</div>

			<div class="ls-slide" data-ls="bgsize:contain;duration:4000;transition2d:73;kenburnszoom:in;">
				<%= image_tag("Commercial/commercial4.jpeg", height:"1000px", width:"1000px", alt:"glas elevator", class:"ls-bg")%>
				<!--img width="1000" height="1000" src="assets/images/Commercial/commercial4.jpeg" class="ls-bg"
					alt="glas elevator"-->
				<p style="font-family:Poppins;font-size:50px;line-height:50px;color:#3d3d3d;top:552px;left:883px;font-weight:600;"
					class="ls-l"
					data-ls="offsetxin:-100%;durationin:600;delayin:400;easingin:easeOutQuint;clipin:0 0 0 100%;offsetxout:-100%;durationout:500;clipout:0 0 0 100%;parallaxlevel:0;">
					Light Style
				</p>
				<p style="letter-spacing:7px;font-family:Poppins;font-size:24px;line-height:24px;color:#a01818;top:602px;left:885px;font-weight:700;"
					class="ls-l"
					data-ls="offsetxin:-100%;durationin:600;delayin:400;easingin:easeOutQuint;clipin:0 0 0 100%;offsetxout:-100%;durationout:500;clipout:0 0 0 100%;parallaxlevel:0;">
					Glass and stainless <br> steel.
				</p>
			</div>

			<div class="ls-slide" data-ls="bgsize:contain;duration:4000;transition2d:73;kenburnszoom:in;">
				<%= image_tag("Commercial/commercial5.jpeg", height:"1000px", width:"1000px", alt:"gold elevator", class:"ls-bg")%>
				<!--img width="1000" height="1000" src="assets/images/Commercial/commercial5.jpeg" class="ls-bg"
					alt="gold elevator"-->
				<p style="letter-spacing:-1px;font-family:Poppins;font-size:50px;line-height:50px;color:#3d3d3d;top:552px;left:883px;font-weight:600;"
					class="ls-l"
					data-ls="offsetxin:-100%;durationin:600;delayin:400;easingin:easeOutQuint;clipin:0 0 0 100%;offsetxout:-100%;durationout:500;clipout:0 0 0 100%;parallaxlevel:0;">
					Custom Style
				</p>
				<p style="letter-spacing:7px;font-family:Poppins;font-size:24px;line-height:24px;color:#a01818;top:602px;left:885px;font-weight:700;"
					class="ls-l"
					data-ls="offsetxin:-100%;durationin:600;delayin:400;easingin:easeOutQuint;clipin:0 0 0 100%;offsetxout:-100%;durationout:500;clipout:0 0 0 100%;parallaxlevel:0;">
				</p>
				
			</div>

		</div>

		<div>
			<br><br><br><br><br><br><br><br>
		</div>

		<!-- Initializing the slider -->
		<script>
			jQuery("#layerslider").layerSlider({
				type: 'responsive',
				skin: 'roundedflat',
				skinsPath: 'assets/skins/',
				thumbnailNavigation: 'always',
				tnContainerWidth: '100%',
				navStartStop: false,
				tnWidth: 180,
				tnHeight: 130
			});
		</script>
		<!---/Initializing the slider-->

		<!-- /SLIDE SECTION -->


		<!-- BUTTON CALLOUT -->
		<a href="index.html#contact" class="btn btn-xlg btn-blue fs-20 fullwidth m-0 rad-0 p-40">
			<span class="font-lato fs-30">
				Contact us to see more styles.
				<strong>Contact us &raquo;</strong>
			</span>
		</a>
		<!-- /BUTTON CALLOUT -->